### ISSUE TITLE
theme for iTerm2?

### ISSUE THREAD

**Issue by karambaq** [tyrannicaltoucan/vim-quantum#10]
Hey, thank you for this beautiful theme. I just wondering is there a similar theme for iTerm2?

**Comment by tyrannicaltoucan** [comment]
Yup! You can find the themes [here](https://github.com/tyrannicaltoucan/vim-quantum/tree/master/term/iterm). If you cloned/downloaded this color scheme already, they can be found wherever you store your vim color schemes. (For example, I use neovim with vim-plug, so mine are found in `~/.local/share/nvim/plugged/vim-quantum/term/iterm`)

**Comment by karambaq** [comment]
@tyrannicaltoucan Whoa, great, thank you again!
