### ISSUE TITLE
Changing ColorColumn color to something that creates less contrast and distraction

### ISSUE THREAD

**Issue by kristijanhusak** [tyrannicaltoucan/vim-quantum#11]
Hi,

First of all, great colorscheme, i really love it.

I would like to suggest to change `ColorColumn` bg color to something that doesn't create so much contrast and distraction.

We could use `StatusLineNC` foreground color (since it's reversed by default), which is `s:gray2` i think.

So this:
![before](https://i.imgur.com/HETqEVP.png)

Becomes this:
![after](https://i.imgur.com/CcZLuyb.png)

This is for the non-black version. I didn't checked the black one.

**Comment by tyrannicaltoucan** [comment]
I definitely agree! I don't usually use `ColorColumn` so I was a little conservative with the contrast.
