### ISSUE TITLE
Terminal Support within Neovim

### ISSUE THREAD

**Issue by gavsim** [tyrannicaltoucan/vim-quantum#2]
Hi,

Great work on this colorscheme! I was wondering if you were looking to add support for the terminal buffer within neovim? I imagine the comments in this thread could be of help? https://github.com/chriskempson/base16-vim/issues/69

Thanks,

**Comment by tyrannicaltoucan** [comment]
Was wanting to do this for a while!

Thanks for reminding me! 😀
