### ISSUE TITLE
Can't enable quantum black

### ISSUE THREAD

**Issue by robertbenjamin** [tyrannicaltoucan/vim-quantum#3]
Absolutely love this theme, but I can't seem to enable quantum black.

I've added `let g:quantum_black=1` in my .vimrc and `:echo quantum_black` returns 1, but after reloading Vim the theme is still set to normal quantum with a noticeably lighter background.

I'm using vim-deep-space for now (also a fantastic theme!), but it would be nice if I could figure out to get this to work.

I'm using Vim 8.0.594 and iTerm 3.1.2.

Thanks!

**Comment by tyrannicaltoucan** [comment]
Are you setting `let g:quantum_black=1` after `colorscheme` by chance?

**Comment by robertbenjamin** [comment]
Shit, that was it — I'm fairly new to Vim and didn't realize the order of global variables matters in Vimscript.

Thanks again for your help, and thanks for making the world a prettier place with your awesome color schemes! Would love a light version of quantum or deep-space sometime in the future 💯

**Comment by tyrannicaltoucan** [comment]
I probably should clarify this in the `README`...

No problem, I enjoy doing this stuff! I've been wanting to add light versions of my colorschemes, just need to find some time to do so! 😁
