### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by ollien** [tyrannicaltoucan/vim-quantum#6]
I was looking to upload this color scheme to my dotfiles repo, but the vim color file only makes the following mention of the license, but no actual license text. 

> " Quantum - A 24-bit Material color scheme for Vim
> " Author: Brandon Siders
> " License: MIT

Would you mind adding a license file to your project so I can include the license text within my dotfiles?

**Comment by tyrannicaltoucan** [comment]
Consider it done!
