### ISSUE TITLE
Not working in tmux

### ISSUE THREAD

**Issue by hannenz** [tyrannicaltoucan/vim-quantum#7]
Hi. I cannnot get this beautiful colorscheme working inside tmux. (Outside tmux it works fine)
I am using pantheon-terminal on elementary os (== ubuntu 16.04) with tmux 2.3 and vim 8.0.
tmux itself is configured to use Tc and it works (checked with the testscript [mentioned here](https://github.com/tmux/tmux/issues/696) )
When I run vim however I get a more or less black and white colorscheme

![namenloses fenster_003](https://user-images.githubusercontent.com/1071312/29773531-315e2e9c-8bfe-11e7-913d-17bae0d0e59d.png)

I dont know if its an issue of the theme or with [my .vimrc](https://github.com/hannenz/dotvim/blob/master/vimrc) or [my .tmux.conf](https://github.com/hannenz/dotfiles/blob/master/files/.tmux.conf)

EDIT: Solved it by following [this](https://www.reddit.com/r/vim/comments/5416d0/true_colors_in_vim_under_tmux/)
Sorry for spamming in here, maybe interesting for other users though?

**Comment by tyrannicaltoucan** [comment]
I might just this info to the README since this seems to be a somewhat common issue.
