### ISSUE TITLE
Not getting the example syntax highlight

### ISSUE THREAD

**Issue by nikonikolov** [tyrannicaltoucan/vim-quantum#9]
Sorry, I am not very experienced in vim and this might be a simple question. I am not getting the same syntax highlight as shown in the example. Instead I am getting this:
![image](https://user-images.githubusercontent.com/11044035/32346377-7eeebb34-c00d-11e7-9b4e-2fa567d11625.png)

The file above is with `.js` extension. I am using vim `7.4.1938` in konsole `4.14.3`. As far as my google search showed, this version of konsole supports true colors. Not sure if all environment variables are set correctly for vim to use them. I manually set `export COLORTERM=truecolor` and `export TERM=xterm-256color` (result was also the same without them).
Here is my `.vimrc`:

```
set number
set ruler
set hlsearch

set autoindent
set smartindent
set expandtab
set softtabstop=2
set shiftwidth=2
set numberwidth=2

set termguicolors
set background=dark
let g:quantum_black=1
colorscheme quantum
```

**Comment by tyrannicaltoucan** [comment]
As you can see, Vim's javascript highlighter isn't super great, so I'm actually using a plugin: [vim-javascript](https://github.com/pangloss/vim-javascript).
